version: "3.3"

services:

  api:
    image: node:11
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3000:3000

volumes:
  db_vol:
